name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t your-docker-image-name .
    - name: Save Docker image
      run: docker save your-docker-image-name | gzip > your-docker-image name.tar.gz
    - name: Upload Docker image
      uses: actions/upload-artifact@v2
      with:
        name: your-docker-image-name
        path: your-docker-image-name.tar.gz
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Docker image
      uses: actions/download-artifact@v2
      with:
        name: your-docker-image-name
    - name: Load Docker image
      run: docker load < your-docker-image-name.tar.gz
    - name: Deploy to Kubernetes
      run: |
        echo "$KUBECONFIG" > kubeconfig.yaml
        kubectl apply -f path-to-your-kubernetes-manifest-file